# -*- coding: utf-8 -*-
"""
自动从JSON转换的配置文件
原文件: room_settings.json
"""

ROOM_CONFIG = {
    "room_name": u"EC起床战争",
    "lobby_dimension": 0,
    "waiting_spawn": {
        "x": 5.5,
        "y": 134.0,
        "z": 104,
    },
    "waiting_spawn_yaw": -90,
    "broadcast_score_spawn": {
        "x": 47,
        "y": 135.0,  # [FIX 2025-11-08] 提高2格,teleport会再+2,最终玩家在137
        "z": 77,
    },
    "broadcast_score_spawn_yaw": 180,
    "broadcast_score_npc_positions": [
        {
            "pos": {
                "x": 47,
                "y": 138,
                "z": 68,
            },
            "yaw": 0,
        },
        {
            "pos": {
                "x": 40.5,
                "y": 137,
                "z": 68,
            },
            "yaw": 0,
        },
        {
            "pos": {
                "x": 53.5,
                "y": 137,
                "z": 68,
            },
            "yaw": 0,
        },
    ],
    "max_players": 10,
    "start_players": 2,
    "countdown_time": 20,
    "stages": [
        {
            "id": "team4_ancient",
            "name": u"上古荒原",
            "image": "textures/ui/map/ancient.jpg",
            "map_dimension": 467909645,
            "mode": "team4",
            "spawn_pos": {
                "x": 0.0,
                "y": 150.0,
                "z": 0.0,
            },
            "center_pos": {
                "x": 0,
                "y": 92,
                "z": 0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_egypt",
            "name": u"法老",
            "image": "textures/ui/map/egypt.jpg",
            "map_dimension": 389335129,
            "mode": "team4",
            "spawn_pos": {
                "x": 0.0,
                "y": 150.0,
                "z": 0.0,
            },
            "center_pos": {
                "x": 0,
                "y": 128,
                "z": 0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_camp",
            "name": u"营地",
            "image": "textures/ui/map/camp.jpg",
            "map_dimension": 401862019,
            "mode": "team4",
            "spawn_pos": {
                "x": 0.0,
                "y": 150.0,
                "z": 0.0,
            },
            "center_pos": {
                "x": 0,
                "y": 128,
                "z": 0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_cutoff",
            "name": u"断权桓",
            "image": "textures/ui/map/cutoff.jpg",
            "map_dimension": 466309523,
            "mode": "team4",
            "spawn_pos": {
                "x": 0.0,
                "y": 150.0,
                "z": 0.0,
            },
            "center_pos": {
                "x": 0,
                "y": 128,
                "z": 0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_beam",
            "name": u"劲梁",
            "image": "textures/ui/map/beam.jpg",
            "map_dimension": 468883074,
            "mode": "team4",
            "spawn_pos": {
                "x": 0.0,
                "y": 150.0,
                "z": 0.0,
            },
            "center_pos": {
                "x": 0,
                "y": 128,
                "z": 0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_fire",
            "name": u"怒火街头",
            "image": "textures/ui/map/fire.jpg",
            "map_dimension": 593472623,
            "mode": "team4",
            "spawn_pos": {
                "x": 0.0,
                "y": 150.0,
                "z": 0.0,
            },
            "center_pos": {
                "x": 0,
                "y": 128,
                "z": 0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_chinatown",
            "name": u"华夏记忆",
            "image": "textures/ui/map/chinatown.jpg",
            "map_dimension": 996687919,
            "mode": "team4",
            "spawn_pos": {
                "x": 0.0,
                "y": 150.0,
                "z": 0.0,
            },
            "center_pos": {
                "x": 0,
                "y": 128,
                "z": 0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_catboutique",
            "name": u"樱猫小铺",
            "image": "textures/ui/map/catboutique.jpg",
            "map_dimension": 10000,
            "mode": "team4",
            "spawn_pos": {
                "x": 0.0,
                "y": 150.0,
                "z": 0.0,
            },
            "center_pos": {
                "x": 0,
                "y": 128,
                "z": 0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_vigilance",
            "name": u"瞭望之海",
            "image": "textures/ui/map/vigilance.jpg",
            "map_dimension": 10001,
            "mode": "team4",
            "spawn_pos": {
                "x": 0.0,
                "y": 150.0,
                "z": 0.0,
            },
            "center_pos": {
                "x": 0,
                "y": 128,
                "z": 0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_steelworks",
            "name": u"钢铁工厂",
            "image": "textures/ui/map/steelworks.jpg",
            "map_dimension": 10002,
            "mode": "team4",
            "spawn_pos": {
                "x": 0.0,
                "y": 150.0,
                "z": 0.0,
            },
            "center_pos": {
                "x": 0,
                "y": 128,
                "z": 0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_sakurawatch",
            "name": u"浮樱守望",
            "image": "textures/ui/map/sakurawatch.jpg",
            "map_dimension": 10003,
            "mode": "team4",
            "spawn_pos": {
                "x": 50.0,
                "y": 130.0,
                "z": 50.0,
            },
            "center_pos": {
                "x": 50,
                "y": 128,
                "z": 50,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_hornwood",
            "name": u"角林驿站",
            "image": "textures/ui/map/hornwood.jpg",
            "map_dimension": 10004,
            "mode": "team4",
            "spawn_pos": {
                "x": 0.0,
                "y": 150.0,
                "z": 0.0,
            },
            "center_pos": {
                "x": 0,
                "y": 128,
                "z": 0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_egg",
            "name": u"龙息",
            "image": "textures/ui/map/egg.jpg",
            "map_dimension": 1010301111,
            "mode": "team4",
            "spawn_pos": {
                "x": 0.0,
                "y": 150.0,
                "z": 0.0,
            },
            "center_pos": {
                "x": 0,
                "y": 128,
                "z": 0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_deadsea",
            "name": u"死海",
            "image": "textures/ui/map/deadsea.jpg",
            "map_dimension": 1506787667,
            "mode": "team4",
            "spawn_pos": {
                "x": 0.0,
                "y": 150.0,
                "z": 0.0,
            },
            "center_pos": {
                "x": 0,
                "y": 128,
                "z": 0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_flag",
            "name": u"战旗",
            "image": "textures/ui/map/flag.jpg",
            "map_dimension": 1522503826,
            "mode": "team4",
            "spawn_pos": {
                "x": 0.0,
                "y": 150.0,
                "z": 0.0,
            },
            "center_pos": {
                "x": 0,
                "y": 128,
                "z": 0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_sakurawatch",
            "name": u"浮樱守望",
            "image": "textures/ui/map/sakurawatch.jpg",
            "map_dimension": 20000,
            "mode": "team2",
            "spawn_pos": {
                "x": 0.0,
                "y": 150.0,
                "z": 200.0,
            },
            "center_pos": {
                "x": 0,
                "y": 128,
                "z": 200,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_steelworks",
            "name": u"钢铁工厂",
            "image": "textures/ui/map/steelworks.jpg",
            "map_dimension": 20001,
            "mode": "team2",
            "spawn_pos": {
                "x": 307.0,
                "y": 141.0,
                "z": 239.0,
            },
            "center_pos": {
                "x": 307,
                "y": 128,
                "z": 239,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_vigilance",
            "name": u"瞭望之海",
            "image": "textures/ui/map/vigilance.jpg",
            "map_dimension": 20002,
            "mode": "team2",
            "spawn_pos": {
                "x": 361.0,
                "y": 159.0,
                "z": 314.0,
            },
            "center_pos": {
                "x": 361,
                "y": 128,
                "z": 314,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_catboutique",
            "name": u"樱猫小铺",
            "image": "textures/ui/map/catboutique.jpg",
            "map_dimension": 20003,
            "mode": "team2",
            "spawn_pos": {
                "x": -21.0,
                "y": 112.0,
                "z": 48.0,
            },
            "center_pos": {
                "x": -21,
                "y": 128,
                "z": 48,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_hornwood",
            "name": u"角林驿站",
            "image": "textures/ui/map/hornwood.jpg",
            "map_dimension": 20004,
            "mode": "team2",
            "spawn_pos": {
                "x": -14.0,
                "y": 122.0,
                "z": 65.0,
            },
            "center_pos": {
                "x": -14,
                "y": 128,
                "z": 65,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_egypt",
            "name": u"法老",
            "image": "textures/ui/map/egypt.jpg",
            "map_dimension": 20005,
            "mode": "team2",
            "spawn_pos": {
                "x": 86.0,
                "y": 146.0,
                "z": 81.0,
            },
            "center_pos": {
                "x": 86,
                "y": 128,
                "z": 81,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_camp",
            "name": u"营地",
            "image": "textures/ui/map/camp.jpg",
            "map_dimension": 20006,
            "mode": "team2",
            "spawn_pos": {
                "x": 74.0,
                "y": 147.0,
                "z": 84.0,
            },
            "center_pos": {
                "x": 74,
                "y": 128,
                "z": 84,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_cutoff",
            "name": u"断权桓",
            "image": "textures/ui/map/cutoff.jpg",
            "map_dimension": 20007,
            "mode": "team2",
            "spawn_pos": {
                "x": 94.0,
                "y": 128.0,
                "z": 79.0,
            },
            "center_pos": {
                "x": 94,
                "y": 128,
                "z": 79,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_ancient",
            "name": u"上古荒原",
            "image": "textures/ui/map/ancient.jpg",
            "map_dimension": 20008,
            "mode": "team2",
            "spawn_pos": {
                "x": 82.0,
                "y": 110.0,
                "z": 80.0,
            },
            "center_pos": {
                "x": 0,
                "y": 92,
                "z": 0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_beam",
            "name": u"劲梁",
            "image": "textures/ui/map/beam.jpg",
            "map_dimension": 20009,
            "mode": "team2",
            "spawn_pos": {
                "x": 79.0,
                "y": 101.0,
                "z": 85.0,
            },
            "center_pos": {
                "x": 79,
                "y": 128,
                "z": 85,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_fire",
            "name": u"怒火街头",
            "image": "textures/ui/map/fire.jpg",
            "map_dimension": 20010,
            "mode": "team2",
            "spawn_pos": {
                "x": 74.0,
                "y": 100.0,
                "z": 74.0,
            },
            "center_pos": {
                "x": 74,
                "y": 128,
                "z": 74,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_chinatown",
            "name": u"华夏记忆",
            "image": "textures/ui/map/chinatown.jpg",
            "map_dimension": 20011,
            "mode": "team2",
            "spawn_pos": {
                "x": 145.0,
                "y": 124.0,
                "z": 236.0,
            },
            "center_pos": {
                "x": 145,
                "y": 128,
                "z": 236,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_egg",
            "name": u"龙息",
            "image": "textures/ui/map/egg.jpg",
            "map_dimension": 20012,
            "mode": "team2",
            "spawn_pos": {
                "x": 82.0,
                "y": 114.0,
                "z": 78.0,
            },
            "center_pos": {
                "x": 82,
                "y": 128,
                "z": 78,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_deadsea",
            "name": u"死海",
            "image": "textures/ui/map/deadsea.jpg",
            "map_dimension": 20013,
            "mode": "team2",
            "spawn_pos": {
                "x": 82.0,
                "y": 100.0,
                "z": 79.0,
            },
            "center_pos": {
                "x": 82,
                "y": 128,
                "z": 79,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_flag",
            "name": u"战旗",
            "image": "textures/ui/map/flag.jpg",
            "map_dimension": 20014,
            "mode": "team2",
            "spawn_pos": {
                "x": 82.0,
                "y": 127.0,
                "z": 103.0,
            },
            "center_pos": {
                "x": 82,
                "y": 128,
                "z": 103,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_asteroids",
            "name": u"月球基地",
            "image": "textures/ui/map/asteroids.jpg",
            "map_dimension": 10005,
            "mode": "team4",
            "spawn_pos": {
                "x": -79.0,
                "y": 126.0,
                "z": 136.0,
            },
            "center_pos": {
                "x": -79.0,
                "y": 126.0,
                "z": 136.0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_atlantis",
            "name": u"末地遗址",
            "image": "textures/ui/map/atlantis.jpg",
            "map_dimension": 10006,
            "mode": "team4",
            "spawn_pos": {
                "x": -40.0,
                "y": 113.0,
                "z": 271.0,
            },
            "center_pos": {
                "x": -40.0,
                "y": 113.0,
                "z": 271.0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_castle",
            "name": u"恶魔行宫",
            "image": "textures/ui/map/castle.jpg",
            "map_dimension": 10007,
            "mode": "team4",
            "spawn_pos": {
                "x": 73.0,
                "y": 120.0,
                "z": 399.0,
            },
            "center_pos": {
                "x": 73.0,
                "y": 120.0,
                "z": 399.0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_chronostasis",
            "name": u"定格时钟",
            "image": "textures/ui/map/chronostasis.jpg",
            "map_dimension": 10008,
            "mode": "team4",
            "spawn_pos": {
                "x": 138.0,
                "y": 130.0,
                "z": 480.0,
            },
            "center_pos": {
                "x": 138.0,
                "y": 130.0,
                "z": 480.0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_clay",
            "name": u"终末宫殿",
            "image": "textures/ui/map/clay.jpg",
            "map_dimension": 10009,
            "mode": "team4",
            "spawn_pos": {
                "x": 246.0,
                "y": 132.0,
                "z": 594.0,
            },
            "center_pos": {
                "x": 246.0,
                "y": 132.0,
                "z": 594.0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_asteroids",
            "name": u"月球基地",
            "image": "textures/ui/map/asteroids.jpg",
            "map_dimension": 20015,
            "mode": "team2",
            "spawn_pos": {
                "x": 141.0,
                "y": 140.0,
                "z": 220.0,
            },
            "center_pos": {
                "x": 141.0,
                "y": 140.0,
                "z": 220.0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_atlantis",
            "name": u"末地遗址",
            "image": "textures/ui/map/atlantis.jpg",
            "map_dimension": 20016,
            "mode": "team2",
            "spawn_pos": {
                "x": 263.0,
                "y": 145.0,
                "z": 321.0,
            },
            "center_pos": {
                "x": 263.0,
                "y": 145.0,
                "z": 321.0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_castle",
            "name": u"恶魔行宫",
            "image": "textures/ui/map/castle.jpg",
            "map_dimension": 20017,
            "mode": "team2",
            "spawn_pos": {
                "x": 395.0,
                "y": 124.0,
                "z": 444.0,
            },
            "center_pos": {
                "x": 395.0,
                "y": 124.0,
                "z": 444.0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_chronostasis",
            "name": u"定格时钟",
            "image": "textures/ui/map/chronostasis.jpg",
            "map_dimension": 20018,
            "mode": "team2",
            "spawn_pos": {
                "x": 454.0,
                "y": 149.0,
                "z": 542.0,
            },
            "center_pos": {
                "x": 454.0,
                "y": 149.0,
                "z": 542.0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_clay",
            "name": u"终末宫殿",
            "image": "textures/ui/map/clay.jpg",
            "map_dimension": 20019,
            "mode": "team2",
            "spawn_pos": {
                "x": 617.0,
                "y": 76.0,
                "z": 671.0,
            },
            "center_pos": {
                "x": 617.0,
                "y": 76.0,
                "z": 671.0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_altar",
            "name": u"碎石阵地",
            "image": "textures/ui/map/altar.jpg",
            "map_dimension": 10010,
            "mode": "team4",
            "spawn_pos": {
                "x": 211.0,
                "y": 119.0,
                "z": 292.0,
            },
            "center_pos": {
                "x": 211.0,
                "y": 119.0,
                "z": 292.0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_child_garden",
            "name": u"彩虹乐园",
            "image": "textures/ui/map/child_garden.jpg",
            "map_dimension": 10011,
            "mode": "team4",
            "spawn_pos": {
                "x": 239.0,
                "y": 110.0,
                "z": 333.0,
            },
            "center_pos": {
                "x": 239.0,
                "y": 110.0,
                "z": 333.0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_fleet",
            "name": u"中转站",
            "image": "textures/ui/map/fleet.jpg",
            "map_dimension": 10012,
            "mode": "team4",
            "spawn_pos": {
                "x": 226.0,
                "y": 140.0,
                "z": 318.0,
            },
            "center_pos": {
                "x": 226.0,
                "y": 140.0,
                "z": 318.0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_flower",
            "name": u"灿星花园",
            "image": "textures/ui/map/flower.jpg",
            "map_dimension": 10013,
            "mode": "team4",
            "spawn_pos": {
                "x": 220.0,
                "y": 142.0,
                "z": 305.0,
            },
            "center_pos": {
                "x": 220.0,
                "y": 142.0,
                "z": 305.0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team4_fortress",
            "name": u"舰炮阵地",
            "image": "textures/ui/map/fortress.jpg",
            "map_dimension": 10014,
            "mode": "team4",
            "spawn_pos": {
                "x": 204.0,
                "y": 124.0,
                "z": 281.0,
            },
            "center_pos": {
                "x": 204.0,
                "y": 124.0,
                "z": 281.0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_altar",
            "name": u"碎石阵地",
            "image": "textures/ui/map/altar.jpg",
            "map_dimension": 20020,
            "mode": "team2",
            "spawn_pos": {
                "x": 213.0,
                "y": 115.0,
                "z": 300.0,
            },
            "center_pos": {
                "x": 213.0,
                "y": 115.0,
                "z": 300.0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_child_garden",
            "name": u"彩虹乐园",
            "image": "textures/ui/map/child_garden.jpg",
            "map_dimension": 20021,
            "mode": "team2",
            "spawn_pos": {
                "x": 345.0,
                "y": 86.0,
                "z": 423.0,
            },
            "center_pos": {
                "x": 345.0,
                "y": 87.0,
                "z": 424.0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_fleet",
            "name": u"中转站",
            "image": "textures/ui/map/fleet.jpg",
            "map_dimension": 20022,
            "mode": "team2",
            "spawn_pos": {
                "x": 349.0,
                "y": 126.0,
                "z": 498.0,
            },
            "center_pos": {
                "x": 349.0,
                "y": 126.0,
                "z": 498.0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_flower",
            "name": u"灿星花园",
            "image": "textures/ui/map/flower.jpg",
            "map_dimension": 20023,
            "mode": "team2",
            "spawn_pos": {
                "x": 398.0,
                "y": 127.0,
                "z": 561.0,
            },
            "center_pos": {
                "x": 398.0,
                "y": 128.0,
                "z": 561.0,
            },
            "backup_radius": 200,
        },
        {
            "id": "team2_fortress",
            "name": u"舰炮阵地",
            "image": "textures/ui/map/fortress.jpg",
            "map_dimension": 20024,
            "mode": "team2",
            "spawn_pos": {
                "x": 463.0,
                "y": 128.0,
                "z": 629.0,
            },
            "center_pos": {
                "x": 462.0,
                "y": 127.0,
                "z": 629.0,
            },
            "backup_radius": 200,
        }
    ],
}
